apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "graceful-drain-controller.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "graceful-drain-controller.labels" . | nindent 4 }}
